### ISSUE TITLE
Pagination position is not reset when moving between files

### ISSUE THREAD

**Issue by jondrummond-codeo** [fluffynuts/diff-buddy#3]
If you use page down on one file then move to another file. the first page down you do on this file will move you to the pagination point you were at when on the previous file resulting in you paging down further than 1 page. e.g. fileA - page down 10 times, next file, page down takes you to 11 pages down.

Not urgent to fix, but just wanted to note it.

**Comment by fluffynuts** [comment]
o that's interesting, but probably an artifact of all the nasty statics :D

**Comment by fluffynuts** [comment]
(`diff-buddy` is a jenga tower of hacks)

**Comment by fluffynuts** [comment]
This should be resolved now (:

**Comment by jondrummond-codeo** [comment]
Thanks @fluffynuts
